# Generated by Django 5.0 on 2023-12-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
    ]
