# Generated by Django 5.0 on 2023-12-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='static/menu_images/brik.png', upload_to='static/menu_images/'),
        ),
    ]
